# Generated by Django 4.2 on 2023-05-15 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('user_image', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Document Status',
                'verbose_name_plural': 'Document Statuses',
            },
        ),
    ]
