# Generated by Django 4.2 on 2023-05-10 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingdocs',
            options={'verbose_name': 'Outgoing Document', 'verbose_name_plural': 'Outgoing Documents'},
        ),
        migrations.AlterField(
            model_name='outgoingdocs',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded'), ('Denied', 'Denied')], default='Pending', max_length=255),
        ),
        migrations.CreateModel(
            name='IncomingDocs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_no', models.CharField(max_length=255, unique=True)),
                ('title_docs', models.CharField(max_length=255, verbose_name='Title of the Document')),
                ('document', models.FileField(upload_to='documents')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded'), ('Denied', 'Denied')], default='Pending', max_length=255)),
                ('date_forwarded', models.DateTimeField(auto_now_add=True)),
                ('tracking_details', models.JSONField(blank=True, null=True)),
                ('doc_actions', models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Signed', 'Signed'), ('Endorsed', 'Endorsed'), ('No Action', 'No Action')], default='No Action', max_length=255)),
                ('forwarded_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_by', to='apps.department')),
                ('type_of_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Document',
                'verbose_name_plural': 'Incoming Documents',
            },
        ),
    ]
