# Generated by Django 4.2 on 2023-05-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_outgoingdocs_options_alter_outgoingdocs_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingdocs',
            name='doc_actions',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Signed', 'Signed'), ('Endorsed', 'Endorsed'), ('No Action', 'No Action')], default='Select an action', max_length=255, verbose_name='Document Actions:'),
        ),
        migrations.AlterField(
            model_name='outgoingdocs',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to='apps.department', verbose_name='Forwarded To:'),
        ),
    ]
