# Generated by Django 4.2 on 2023-05-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_documentstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentStatus',
        ),
    ]
