# Generated by Django 4.2 on 2023-05-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_outgoingdocs_doc_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingdocs',
            name='doc_actions',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Signed', 'Signed'), ('Endorsed', 'Endorsed'), ('No Action', 'No Action')], default='No Action', max_length=255, verbose_name='Document Actions:'),
        ),
    ]
