# Generated by Django 4.2 on 2023-05-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_outgoingdocs_doc_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingdocs',
            old_name='forwarded_to',
            new_name='receiver',
        ),
    ]
